### ISSUE TITLE
Object.values(...).flat is not a function

### ISSUE THREAD

**Issue by imcodingideas** [benawad/butler-cli#2]
I am trying to run this on a project with: `npx butler-cli src` and I'm getting: `Object.values(...).flat is not a function` returned. Let me share with you my envirement. 

```
/Users/jchambers/.nvm/versions/node/v10.15.0/bin/node
```

NPM version: 6.4.1

I thought I would submit a bug report.

**Comment by benawad** [comment]
Thanks for the report, I published a new version 2 seconds ago, that should fix this. Could you try it again and see if it works for you?

**Comment by imcodingideas** [comment]
It still is the same thing. I wonder if `npx` is cached.

**Comment by benawad** [comment]
oops it's me, I forgot to build TypeScript before publishing 😂

**Comment by benawad** [comment]
just tested on Node v8, should work now
