### ISSUE TITLE
Path are messed up on Windows

### ISSUE THREAD

**Issue by Reidond** [benawad/butler-cli#4]
Here is a example screenshot:

![image](https://user-images.githubusercontent.com/20406775/74551790-87abf300-4f5c-11ea-95f9-8d146d51c081.png)

Repo: [vscode-hemtt](https://github.com/Reidond/vscode-hemtt/tree/feature/try_buttler_on_repo/src)

**Comment by Reidond** [comment]
Looks like "./" is normal for windows. The problem might be in path module

**Comment by benawad** [comment]
should be fixed now https://github.com/benawad/butler-cli/commit/cb59780545bf3fb396954d8102665fe06d010133
